/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pt_com_gmv_lab_implant_jni_ARToolkitPlus */

#ifndef _Included_pt_com_gmv_lab_implant_jni_ARToolkitPlus
#define _Included_pt_com_gmv_lab_implant_jni_ARToolkitPlus
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pt_com_gmv_lab_implant_jni_ARToolkitPlus
 * Method:    setup
 * Signature: (IIIIIII)V
 */
JNIEXPORT void JNICALL Java_pt_com_gmv_lab_implant_jni_ARToolkitPlus_setup
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     pt_com_gmv_lab_implant_jni_ARToolkitPlus
 * Method:    init
 * Signature: (Ljava/lang/String;FF)Z
 */
JNIEXPORT jboolean JNICALL Java_pt_com_gmv_lab_implant_jni_ARToolkitPlus_init
  (JNIEnv *, jclass, jstring, jfloat, jfloat);

/*
 * Class:     pt_com_gmv_lab_implant_jni_ARToolkitPlus
 * Method:    changeCameraSize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_pt_com_gmv_lab_implant_jni_ARToolkitPlus_changeCameraSize
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     pt_com_gmv_lab_implant_jni_ARToolkitPlus
 * Method:    setPixelFormat
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_pt_com_gmv_lab_implant_jni_ARToolkitPlus_setPixelFormat
  (JNIEnv *, jclass, jint);

/*
 * Class:     pt_com_gmv_lab_implant_jni_ARToolkitPlus
 * Method:    setLoadUndistortionLUT
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_pt_com_gmv_lab_implant_jni_ARToolkitPlus_setLoadUndistortionLUT
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     pt_com_gmv_lab_implant_jni_ARToolkitPlus
 * Method:    setPoseEstimator
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_pt_com_gmv_lab_implant_jni_ARToolkitPlus_setPoseEstimator
  (JNIEnv *, jclass, jint);

/*
 * Class:     pt_com_gmv_lab_implant_jni_ARToolkitPlus
 * Method:    activateVignettingCompensation
 * Signature: (ZIII)V
 */
JNIEXPORT void JNICALL Java_pt_com_gmv_lab_implant_jni_ARToolkitPlus_activateVignettingCompensation
  (JNIEnv *, jclass, jboolean, jint, jint, jint);

/*
 * Class:     pt_com_gmv_lab_implant_jni_ARToolkitPlus
 * Method:    setPatternWidth
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_pt_com_gmv_lab_implant_jni_ARToolkitPlus_setPatternWidth
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     pt_com_gmv_lab_implant_jni_ARToolkitPlus
 * Method:    setBorderWidth
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_pt_com_gmv_lab_implant_jni_ARToolkitPlus_setBorderWidth
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     pt_com_gmv_lab_implant_jni_ARToolkitPlus
 * Method:    setThreshold
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_pt_com_gmv_lab_implant_jni_ARToolkitPlus_setThreshold
  (JNIEnv *, jclass, jint);

/*
 * Class:     pt_com_gmv_lab_implant_jni_ARToolkitPlus
 * Method:    getThreshold
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_pt_com_gmv_lab_implant_jni_ARToolkitPlus_getThreshold
  (JNIEnv *, jclass);

/*
 * Class:     pt_com_gmv_lab_implant_jni_ARToolkitPlus
 * Method:    activateAutoThreshold
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_pt_com_gmv_lab_implant_jni_ARToolkitPlus_activateAutoThreshold
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     pt_com_gmv_lab_implant_jni_ARToolkitPlus
 * Method:    isAutoThresholdActivated
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_pt_com_gmv_lab_implant_jni_ARToolkitPlus_isAutoThresholdActivated
  (JNIEnv *, jclass);

/*
 * Class:     pt_com_gmv_lab_implant_jni_ARToolkitPlus
 * Method:    setNumAutoThresholdRetries
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_pt_com_gmv_lab_implant_jni_ARToolkitPlus_setNumAutoThresholdRetries
  (JNIEnv *, jclass, jint);

/*
 * Class:     pt_com_gmv_lab_implant_jni_ARToolkitPlus
 * Method:    setUndistortionMode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_pt_com_gmv_lab_implant_jni_ARToolkitPlus_setUndistortionMode
  (JNIEnv *, jclass, jint);

/*
 * Class:     pt_com_gmv_lab_implant_jni_ARToolkitPlus
 * Method:    setMarkerMode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_pt_com_gmv_lab_implant_jni_ARToolkitPlus_setMarkerMode
  (JNIEnv *, jclass, jint);

/*
 * Class:     pt_com_gmv_lab_implant_jni_ARToolkitPlus
 * Method:    setImageProcessingMode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_pt_com_gmv_lab_implant_jni_ARToolkitPlus_setImageProcessingMode
  (JNIEnv *, jclass, jint);

/*
 * Class:     pt_com_gmv_lab_implant_jni_ARToolkitPlus
 * Method:    getBitsPerPixel
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_pt_com_gmv_lab_implant_jni_ARToolkitPlus_getBitsPerPixel
  (JNIEnv *, jclass);

/*
 * Class:     pt_com_gmv_lab_implant_jni_ARToolkitPlus
 * Method:    addPattern
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_pt_com_gmv_lab_implant_jni_ARToolkitPlus_addPattern
  (JNIEnv *, jclass, jstring);

/*
 * Class:     pt_com_gmv_lab_implant_jni_ARToolkitPlus
 * Method:    detectMarkers
 * Signature: ([B)[I
 */
JNIEXPORT jintArray JNICALL Java_pt_com_gmv_lab_implant_jni_ARToolkitPlus_detectMarkers
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     pt_com_gmv_lab_implant_jni_ARToolkitPlus
 * Method:    selectBestMarkerByCf
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_pt_com_gmv_lab_implant_jni_ARToolkitPlus_selectBestMarkerByCf
  (JNIEnv *, jclass);

/*
 * Class:     pt_com_gmv_lab_implant_jni_ARToolkitPlus
 * Method:    selectDetectedMarker
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_pt_com_gmv_lab_implant_jni_ARToolkitPlus_selectDetectedMarker
  (JNIEnv *, jclass, jint);

/*
 * Class:     pt_com_gmv_lab_implant_jni_ARToolkitPlus
 * Method:    getConfidence
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_pt_com_gmv_lab_implant_jni_ARToolkitPlus_getConfidence
  (JNIEnv *, jclass);

/*
 * Class:     pt_com_gmv_lab_implant_jni_ARToolkitPlus
 * Method:    getModelViewMatrix
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_pt_com_gmv_lab_implant_jni_ARToolkitPlus_getModelViewMatrix
  (JNIEnv *, jclass);

/*
 * Class:     pt_com_gmv_lab_implant_jni_ARToolkitPlus
 * Method:    getProjectionMatrix
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_pt_com_gmv_lab_implant_jni_ARToolkitPlus_getProjectionMatrix
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
