/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pt_com_gmv_lab_implant_jni_ImageProcessing */

#ifndef _Included_pt_com_gmv_lab_implant_jni_ImageProcessing
#define _Included_pt_com_gmv_lab_implant_jni_ImageProcessing
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pt_com_gmv_lab_implant_jni_ImageProcessing
 * Method:    yuv420sp2rgb
 * Signature: ([BIII[B)V
 */
JNIEXPORT void JNICALL Java_pt_com_gmv_lab_implant_jni_ImageProcessing_yuv420sp2rgb
  (JNIEnv *, jobject, jbyteArray, jint, jint, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
